#########################
# Application Configuration
#########################

[auth]
authorize_url = "https://api.schwabapi.com/v1/oauth/authorize"
auth_url = "https://api.schwabapi.com/v1/oauth/authorize"  # alias used by AuthManager
token_url     = "https://api.schwabapi.com/v1/oauth/token"
base_url      = "https://api.schwabapi.com/v1"  # base API URL for real calls (quotes, etc.)
client_type   = "confidential"
client_auth_method = "basic"
scope = "quotes.read historical.read options.read timesales.read"
simulate = true
# PKCE settings (added per Implementation_Guidelines_HPF #2)
pkce = true
pkce_method = "S256"
registered_uris = [
    "http://127.0.0.1:5000/callback",
    "https://127.0.0.1:8443/auth/redirect"
]

[env.dev]
redirect_uri = "http://127.0.0.1:5000/callback"
host = "127.0.0.1"
port = 5000

[env.prod]
redirect_uri = "https://127.0.0.1:8443/auth/redirect"
host = "0.0.0.0"
port = 8443

[providers.schwab]
# Base URL for the Schwab market data API (overrides auth.base_url for data calls)
# Can be overridden via environment variable SCHWAB_MARKETDATA_BASE
marketdata_base = "https://api.schwabapi.com/v1/marketdata"

[runtime]
storage_root = "./market_data"
token_expiry_warning_minutes = 10
token_cache = "token_cache.json"  # fallback
pkce_state_file = "pkce_state.json"

[metrics]
iv_window_days = 252

[timesales]
nbbo_window_ms = 1000
price_epsilon  = 0.000001

[retries]
max_attempts = 5
initial_seconds = 1
max_seconds = 30

[logging]
level = "DEBUG"
rotate_when = "midnight"
backup_count = 7

[universe]
tickers = ["/ES", "/NQ"]
intervals = ["15m", "4hr", "daily"]
sessions = ["RTH", "24h"]
backfill_days_intraday = 30
backfill_days_daily = 365
options_scope = "summary"
tape_scope = "RTH_full"

[database]
dsn = "sqlite:///./.cache/dev/state.db"
required = false
