[auth]
authorize_url = "https://api.schwabapi.com/v1/oauth/authorize"
token_url     = "https://api.schwabapi.com/v1/oauth/token"
client_type   = "confidential"
client_auth_method = "basic"
scope         = "quotes.read historical.read options.read timesales.read"
pkce          = true
pkce_method   = "S256"
simulate      = true

registered_uris = [
  "https://127.0.0.1:5000/oauth2/callback",
  "https://127.0.0.1:3000/auth/redirect",
  "https://127.0.0.1:8443/auth/redirect"
]

[env.dev]
redirect_uri = "https://127.0.0.1:5000/oauth2/callback"
host = "127.0.0.1"
port = 5000

[runtime]
token_cache = "token_cache.json"
pkce_state_file = "pkce_state.json"
