name: docs-lint
on:
  pull_request:
  push:
    paths:
      - '**/*.md'
      - '.markdownlint.json'
jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Markdownlint
        uses: docker://ghcr.io/igorshubovych/markdownlint-cli:latest
        with:
          args: "**/*.md"
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: mdformat (check only)
        run: |
          python -m pip install --upgrade pip
          pip install mdformat
          mdformat --check .
