name: CI
on:
  push:
    branches: [ main, feat/** ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pip-audit
      - name: Healthcheck
        run: python -m app.main healthcheck
      - name: Tests
        run: pytest -q
      - name: Dependency Vulnerability Audit
        run: pip-audit --strict || (echo "Dependency vulnerabilities found" && exit 1)
  # Uncomment the block below (and add repo secrets) to exercise a real OAuth round-trip
  # - name: Real OAuth Smoke
  #   if: false  # flip to true when ready
  #   env:
  #     CLIENT_ID: ${{ secrets.SCHWAB_CLIENT_ID }}
  #     CLIENT_SECRET: ${{ secrets.SCHWAB_CLIENT_SECRET }}
  #     AUTH_SIMULATE: "false"
  #   run: |
  #     python -m app.main auth-smoke
