name: Production Safety Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  production-safety-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    
    - name: Run Production Safety Verification
      run: |
        python tests/verify_production_safety.py
      env:
        FAIL_ON_STUB: "1"  # Force production mode for CI
    
    - name: Run Unit Tests (Production Safety)
      run: |
        python -m pytest tests/test_production_safety.py -v
      env:
        FAIL_ON_STUB: "1"
    
    - name: Run CLI Contract Tests
      run: |
        python -m pytest tests/test_cli_contracts.py -v
      env:
        FAIL_ON_STUB: "0"  # Allow controlled testing
    
    - name: Run Integration Tests
      run: |
        python -m pytest tests/test_integration.py -v
      env:
        FAIL_ON_STUB: "0"  # Allow mocked testing
    
    - name: Verify No Stub Execution in Production
      run: |
        python -c "
        import os, subprocess, sys
        os.environ['FAIL_ON_STUB'] = '1'
        result = subprocess.run([sys.executable, 'ta_production.py', 'calc-levels', '--symbol', '/NQ', '--date', '2025-08-18', '--format', 'json'], capture_output=True, text=True)
        if result.returncode == 0:
            print('CRITICAL: calc-levels succeeded in production mode!')
            sys.exit(1)
        error_output = result.stdout + result.stderr
        expected_errors = ['E-STUB-PATH', 'E-NODATA-DAILY', 'E-NODATA-INTRADAY']
        if any(error in error_output for error in expected_errors):
            print('PASS: calc-levels correctly failed in production mode')
        else:
            print('FAIL: Unexpected error output:', error_output)
            sys.exit(1)
        "
      env:
        FAIL_ON_STUB: "1"
