---
name: workflow-lint
"on":
  pull_request:
  push:
    paths:
      - .github/workflows/*.yml
      - .github/workflows/*.yaml

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: actionlint
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows/
